apiVersion: cloudstate.io/v1alpha1
kind: StatefulStore
metadata:
  name: my-postgres-store
spec:
  type: Postgres 
  deployment: Unmanaged 
  config: 
    service: postgres-postgresql.default.svc.cluster.local
    credentialsFromSecret:
      name: postgres-credentials
---
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: orders-service
  labels:
    app: orders-service
spec:
  datastore:
    # Name of a deployed Datastore to use.
    name: my-postgres-store
  containers:
    - image: qcllee/orders:latest
---
apiVersion: v1
kind: Service
metadata:
  name: orders-expose
spec:
  type: LoadBalancer
  ports:
    - port: 2000
      targetPort: 8013
  selector:
    app: orders-service
