apiVersion: cloudstate.io/v1alpha1
kind: StatefulStore
metadata:
  name: inmemory-stock
spec:
  type: InMemory
---
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: stock-service
  labels:
    app: stock-service
spec:
  datastore:
    # Name of a deployed Datastore to use.
    name: inmemory-stock
  containers:
    - image: qcllee/orders:latest
---
apiVersion: v1
kind: Service
metadata:
  name: stock-expose
spec:
  type: LoadBalancer
  ports:
    - port: 1981
      targetPort: 8013
  selector:
    app: stock-service
